services:
  db:
    image: postgres:16-alpine
    container_name: pvz-postgres
    environment:
      POSTGRES_DB: pvz_db
      POSTGRES_USER: pvz_user
      POSTGRES_PASSWORD: pvz_password
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    networks:
      - my-network


  app:
    container_name: pvz-system
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=pvz_user
      - DB_PASSWORD=pvz_password
      - DB_NAME=pvz_db
    ports:
      - "8080:8080"
    networks:
      - my-network


networks:
  my-network:

